<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Producto::truncate(); //Avoids duplicates

        $productos = [
            [
                'nombre' => 'Cereza',
                'variedad' => 'Burlat',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/burlat.jpg',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Burlat',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/burlat.jpg',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Early Lory',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/earlyLory.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Early Lory',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/earlyLory.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Brooks',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/brooks.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Brooks',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/brooks.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Prime Giant',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/primeGiant.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Prime Giant',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/primeGiant.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Garnet',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/garnet.jpeg',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Garnet',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/garnet.jpeg',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'New Star',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/newStar.jpeg',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'New Star',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/newStar.jpeg',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Van',
                'formato' => '2kg',
                'precio' => 9.50,
                'imagen' => 'imgs/Productos/Cerezas/van.jpg',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Cereza',
                'variedad' => 'Van',
                'formato' => '5kg',
                'precio' => 22.50,
                'imagen' => 'imgs/Productos/Cerezas/van.jpg',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Albaricoque',
                'variedad' => 'Rojo Pasión',
                'formato' => '2kg',
                'precio' => 8.50,
                'imagen' => 'imgs/Productos/Albaricoques/rojoPasion.jpg',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Albaricoque',
                'variedad' => 'Rojo Pasión',
                'formato' => '5kg',
                'precio' => 19.50,
                'imagen' => 'imgs/Productos/Albaricoques/rojoPasion.jpg',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Gales',
                'formato' => '2kg',
                'precio' => 12.00,
                'imagen' => 'imgs/Productos/Nueces/gales.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Gales',
                'formato' => '5kg',
                'precio' => 28.00,
                'imagen' => 'imgs/Productos/Nueces/gales.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Tulare',
                'formato' => '2kg',
                'precio' => 12.00,
                'imagen' => 'imgs/Productos/Nueces/tulare.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Tulare',
                'formato' => '5kg',
                'precio' => 28.00,
                'imagen' => 'imgs/Productos/Nueces/tulare.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Serr',
                'formato' => '2kg',
                'precio' => 12.00,
                'imagen' => 'imgs/Productos/Nueces/serr.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Serr',
                'formato' => '5kg',
                'precio' => 28.00,
                'imagen' => 'imgs/Productos/Nueces/serr.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Hartley',
                'formato' => '2kg',
                'precio' => 12.00,
                'imagen' => 'imgs/Productos/Nueces/hartley.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Hartley',
                'formato' => '5kg',
                'precio' => 28.00,
                'imagen' => 'imgs/Productos/Nueces/hartley.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Howard',
                'formato' => '2kg',
                'precio' => 12.00,
                'imagen' => 'imgs/Productos/Nueces/howard.png',
                'stock' => 10,
                'disponible' => true,
                'compra_online' => true,
            ],
            [
                'nombre' => 'Nuez',
                'variedad' => 'Howard',
                'formato' => '5kg',
                'precio' => 28.00,
                'imagen' => 'imgs/Productos/Nueces/howard.png',
                'stock' => 4,
                'disponible' => true,
                'compra_online' => true,
            ],
        ];

        Producto::insert($productos);
    }
}
